package mailcow

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/l-with/terraform-provider-mailcow/api"
)

// The Mailcow API only has add and edit endpoints for MTA-STS (no get, no delete).
// Read fetches the public policy page instead (see mtaStsFetchPolicy), and Delete
// deactivates the policy.

func resourceMtaSts() *schema.Resource {
	return &schema.Resource{
		Description: "MTA-STS policy of a domain, served by Mailcow at `https://mta-sts.<domain>/.well-known/mta-sts.txt`. " +
			"The Mailcow API has no read or delete endpoint for MTA-STS, so the provider reads the public policy page " +
			"(requested from `host_name` with `Host: mta-sts.<domain>`, no dependency on the domain's own DNS or certificate). " +
			"That page only exists while the policy is active: the content of an inactive policy can't be read. " +
			"Destroying the resource deactivates the policy (Mailcow removes it only when the domain is deleted).",

		CreateContext: resourceMtaStsCreate,
		ReadContext:   resourceMtaStsRead,
		UpdateContext: resourceMtaStsUpdate,
		DeleteContext: resourceMtaStsDelete,
		CustomizeDiff: resourceMtaStsCustomizeDiff,

		Importer: &schema.ResourceImporter{
			StateContext: resourceMtaStsImport,
		},

		Schema: map[string]*schema.Schema{
			"domain": {
				Type:        schema.TypeString,
				Description: "Domain the policy applies to",
				Required:    true,
				ForceNew:    true,
			},
			"mode": {
				Type:         schema.TypeString,
				Description:  "Policy mode: enforce, testing or none",
				Optional:     true,
				Default:      "enforce",
				ValidateFunc: validation.StringInSlice([]string{"enforce", "testing", "none"}, false),
			},
			"mx": {
				Type:        schema.TypeList,
				Description: "MX hosts allowed by the policy (wildcards like `*.example.com` are allowed)",
				Required:    true,
				MinItems:    1,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"max_age": {
				Type:         schema.TypeInt,
				Description:  "How long senders may cache the policy, in seconds (max 31536000)",
				Optional:     true,
				Default:      604800,
				ValidateFunc: validation.IntBetween(1, 31536000),
			},
			"active": {
				Type:        schema.TypeBool,
				Description: "Whether Mailcow serves the policy",
				Optional:    true,
				Default:     true,
			},
			"policy_id": {
				Type: schema.TypeString,
				Description: "Policy id for the `_mta-sts` TXT record (`v=STSv1; id=<policy_id>;`). " +
					"Generated by the provider (UTC, YYYYMMDDHHMMSS) on create and whenever mode, mx, max_age or active change. " +
					"Mailcow keeps its own id, which the API doesn't expose, so Mailcow's DNS check page may show a different id; " +
					"senders only compare the id with the one they cached, so this is harmless.",
				Computed: true,
			},
		},
	}
}

func resourceMtaStsImport(_ context.Context, d *schema.ResourceData, _ interface{}) ([]*schema.ResourceData, error) {
	if err := d.Set("domain", d.Id()); err != nil {
		return nil, err
	}
	return []*schema.ResourceData{d}, nil
}

func resourceMtaStsCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*APIClient)
	domain := d.Get("domain").(string)

	if err := mtaStsAdd(ctx, c, d, "resourceMtaStsCreate"); err != nil {
		// A policy that already exists in Mailcow can't be added again: adopt it with an edit.
		if !strings.Contains(err.Error(), "Duplicate entry") {
			return diag.FromErr(err)
		}
		if err := mtaStsEdit(ctx, c, d, "resourceMtaStsCreate"); err != nil {
			return diag.FromErr(err)
		}
	}

	d.SetId(domain)
	if err := d.Set("policy_id", mtaStsPolicyId(time.Now())); err != nil {
		return diag.FromErr(err)
	}
	return resourceMtaStsRead(ctx, d, m)
}

func resourceMtaStsRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*APIClient)

	policy, err := mtaStsFetchPolicy(ctx, c.httpClient, c.hostName, d.Id())
	if err != nil {
		return diag.FromErr(err)
	}
	if policy == nil {
		// Missing or inactive: Mailcow doesn't tell which. Keep the rest of the state.
		if err := d.Set("active", false); err != nil {
			return diag.FromErr(err)
		}
		return nil
	}

	if err := d.Set("domain", d.Id()); err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("mode", policy.mode); err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("mx", policy.mx); err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("max_age", policy.maxAge); err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("active", true); err != nil {
		return diag.FromErr(err)
	}
	return nil
}

func resourceMtaStsUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*APIClient)

	if err := mtaStsEdit(ctx, c, d, "resourceMtaStsUpdate"); err != nil {
		// Mailcow answers access_denied when it has no policy for the domain (removed outside Terraform): add it back.
		if !strings.Contains(err.Error(), "access_denied") {
			return diag.FromErr(err)
		}
		if err := mtaStsAdd(ctx, c, d, "resourceMtaStsUpdate"); err != nil {
			return diag.FromErr(err)
		}
	}

	if mtaStsPolicyChanged(d) || d.Get("policy_id").(string) == "" {
		if err := d.Set("policy_id", mtaStsPolicyId(time.Now())); err != nil {
			return diag.FromErr(err)
		}
	}
	return resourceMtaStsRead(ctx, d, m)
}

func resourceMtaStsDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	c := m.(*APIClient)

	// Mailcow fills omitted fields from the stored policy, but returns the version
	// as "STSv1" and then rejects it (version_invalid): always send it.
	mailcowUpdateRequest := api.NewUpdateMtaStsRequest()
	mailcowUpdateRequest.SetAttr("version", "stsv1")
	mailcowUpdateRequest.SetAttr("active", false)
	mailcowUpdateRequest.SetItem(d.Id())

	response, err := api.MailcowUpdateExecute(ctx, c.client, mailcowUpdateRequest)
	if err != nil {
		return diag.FromErr(err)
	}
	err = checkResponse(response, "resourceMtaStsDelete", d.Id())
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId("")
	return nil
}

func resourceMtaStsCustomizeDiff(_ context.Context, d *schema.ResourceDiff, _ interface{}) error {
	if d.Id() == "" {
		return nil
	}
	if mtaStsPolicyChanged(d) || d.Get("policy_id").(string) == "" {
		return d.SetNewComputed("policy_id")
	}
	return nil
}

func mtaStsAdd(ctx context.Context, c *APIClient, d *schema.ResourceData, resourceName string) error {
	mailcowCreateRequest := api.NewCreateMtaStsRequest()
	mailcowCreateRequest.Set("domain", d.Get("domain").(string))
	mailcowCreateRequest.Set("version", "stsv1")
	mailcowCreateRequest.Set("mode", d.Get("mode").(string))
	mailcowCreateRequest.Set("mx", mtaStsMx(d.Get("mx").([]interface{})))
	mailcowCreateRequest.Set("max_age", d.Get("max_age").(int))
	mailcowCreateRequest.Set("active", d.Get("active").(bool))

	request := c.client.Api.MailcowCreate(ctx).MailcowCreateRequest(*mailcowCreateRequest)
	response, _, err := c.client.Api.MailcowCreateExecute(request)
	if err != nil {
		return err
	}
	return checkResponse(response, resourceName, d.Get("domain").(string))
}

// mtaStsEdit sends the whole policy to the edit endpoint. Mailcow only bumps its
// own id when version, mode, mx or max_age differ from what it has.
func mtaStsEdit(ctx context.Context, c *APIClient, d *schema.ResourceData, resourceName string) error {
	mailcowUpdateRequest := api.NewUpdateMtaStsRequest()
	mailcowUpdateRequest.SetAttr("version", "stsv1")
	mailcowUpdateRequest.SetAttr("mode", d.Get("mode").(string))
	mailcowUpdateRequest.SetAttr("mx", mtaStsMx(d.Get("mx").([]interface{})))
	mailcowUpdateRequest.SetAttr("max_age", d.Get("max_age").(int))
	mailcowUpdateRequest.SetAttr("active", d.Get("active").(bool))
	mailcowUpdateRequest.SetItem(d.Get("domain").(string))

	response, err := api.MailcowUpdateExecute(ctx, c.client, mailcowUpdateRequest)
	if err != nil {
		return err
	}
	return checkResponse(response, resourceName, d.Get("domain").(string))
}

type mtaStsChangeDetector interface {
	HasChange(key string) bool
}

func mtaStsPolicyChanged(d mtaStsChangeDetector) bool {
	return d.HasChange("mode") || d.HasChange("mx") || d.HasChange("max_age") || d.HasChange("active")
}

// mtaStsMx joins the MX hosts the way Mailcow expects them (comma separated).
func mtaStsMx(mx []interface{}) string {
	hosts := make([]string, 0, len(mx))
	for _, host := range mx {
		hosts = append(hosts, strings.TrimSpace(host.(string)))
	}
	return strings.Join(hosts, ",")
}

// mtaStsPolicyId formats a policy id like Mailcow does (YYYYMMDDHHMMSS), in UTC.
func mtaStsPolicyId(t time.Time) string {
	return t.UTC().Format("20060102150405")
}

type mtaStsPolicy struct {
	mode   string
	mx     []string
	maxAge int
}

// mtaStsFetchPolicy reads the policy from Mailcow's public page, the one sending servers fetch.
// Mailcow picks the domain from the Host header, so the request goes to the Mailcow host itself
// (TLS checked against host_name) with Host: mta-sts.<domain>. It returns nil when Mailcow
// answers 404, which means no policy or an inactive one.
func mtaStsFetchPolicy(ctx context.Context, httpClient *http.Client, hostName, domain string) (*mtaStsPolicy, error) {
	url := "https://" + hostName + "/.well-known/mta-sts.txt"
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Host = "mta-sts." + domain

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("reading MTA-STS policy of %s from %s: %w", domain, url, err)
	}
	defer resp.Body.Close()

	switch resp.StatusCode {
	case http.StatusNotFound:
		return nil, nil
	case http.StatusOK:
	default:
		return nil, fmt.Errorf("reading MTA-STS policy of %s from %s: HTTP %d", domain, url, resp.StatusCode)
	}

	body, err := io.ReadAll(io.LimitReader(resp.Body, 64*1024))
	if err != nil {
		return nil, err
	}
	policy, err := mtaStsParsePolicy(string(body))
	if err != nil {
		return nil, fmt.Errorf("reading MTA-STS policy of %s: %w", domain, err)
	}
	return policy, nil
}

// mtaStsParsePolicy parses the policy text (RFC 8461 section 3.2: "key: value" lines, mx repeated).
func mtaStsParsePolicy(text string) (*mtaStsPolicy, error) {
	policy := &mtaStsPolicy{mx: []string{}}
	for _, line := range strings.Split(text, "\n") {
		key, value, found := strings.Cut(strings.TrimSpace(line), ":")
		if !found {
			continue
		}
		value = strings.TrimSpace(value)
		switch strings.TrimSpace(key) {
		case "mode":
			policy.mode = value
		case "mx":
			policy.mx = append(policy.mx, value)
		case "max_age":
			maxAge, err := strconv.Atoi(value)
			if err != nil {
				return nil, fmt.Errorf("invalid max_age %q", value)
			}
			policy.maxAge = maxAge
		}
	}
	if policy.mode == "" || len(policy.mx) == 0 || policy.maxAge == 0 {
		return nil, fmt.Errorf("incomplete policy: %q", text)
	}
	return policy, nil
}
